/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package ai.propay.invoices.openapi.api;

import ai.propay.invoices.openapi.model.Comment;
import ai.propay.invoices.openapi.model.Event;
import ai.propay.invoices.openapi.model.FileTags;
import ai.propay.invoices.openapi.model.InvoicePage;
import ai.propay.invoices.openapi.model.InvoicePatch;
import ai.propay.invoices.openapi.model.InvoiceWrapper;
import ai.propay.invoices.openapi.model.PurchaseOrder;
import ai.propay.invoices.openapi.model.Response;
import ai.propay.invoices.openapi.model.Revision;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-09-03T16:59:44.174379100+05:30[Asia/Calcutta]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "invoices", description = "the invoices API")
public interface InvoicesApi {

    /**
     * POST /invoices/api/v1 : Create a new invoice
     *
     * @param invoice List of files to upload (required)
     * @param po  (required)
     * @return Successfully created a new invoice (status code 201)
     *         or Invalid input (status code 400)
     */
    @Operation(
        operationId = "createInvoice",
        summary = "Create a new invoice",
        responses = {
            @ApiResponse(responseCode = "201", description = "Successfully created a new invoice", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response.class))
            }),
            @ApiResponse(responseCode = "400", description = "Invalid input")
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/invoices/api/v1",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<Response> createInvoice(
        @Parameter(name = "invoice", description = "List of files to upload", required = true) @RequestPart(value = "invoice", required = true) MultipartFile invoice,
        @Parameter(name = "po", description = "", required = true) @Valid @RequestPart(value = "po", required = true) PurchaseOrder po
    );


    /**
     * GET /invoices/api/v1/{id}/download/{fileId} : Your GET endpoint
     * Retrieves a single file related to the given ID and file ID.
     *
     * @param id  (required)
     * @param fileId  (required)
     * @return Requested File. (status code 200)
     *         or Not Found (status code 404)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "downloadFile",
        summary = "Your GET endpoint",
        description = "Retrieves a single file related to the given ID and file ID.",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "Requested File.", content = {
                @Content(mediaType = "application/zip", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "404", description = "Not Found"),
            @ApiResponse(responseCode = "500", description = "Internal Server Error")
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1/{id}/download/{fileId}",
        produces = { "application/zip" }
    )
    
    ResponseEntity<org.springframework.core.io.Resource> downloadFile(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "fileId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("fileId") String fileId
    );


    /**
     * GET /invoices/api/v1 : Retrieve all invoices
     *
     * @param pageNumber  (required)
     * @param pageSize  (required)
     * @return A list of invoices (status code 200)
     */
    @Operation(
        operationId = "getAllInvoices",
        summary = "Retrieve all invoices",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of invoices", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoicePage.class)),
                @Content(mediaType = "application/xml", schema = @Schema(implementation = InvoicePage.class)),
                @Content(mediaType = "multipart/form-data", schema = @Schema(implementation = InvoicePage.class)),
                @Content(mediaType = "text/html", schema = @Schema(implementation = InvoicePage.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1",
        produces = { "application/json", "application/xml", "multipart/form-data", "text/html" }
    )
    
    ResponseEntity<InvoicePage> getAllInvoices(
        @NotNull @Parameter(name = "pageNumber", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageNumber", required = true) Integer pageNumber,
        @NotNull @Parameter(name = "pageSize", description = "", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize
    );


    /**
     * GET /invoices/api/v1/{id}/events : Get all events of PR
     * 
     *
     * @param id  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getEvents",
        summary = "Get all events of PR",
        description = "",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Event.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1/{id}/events",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<Event>> getEvents(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * GET /invoices/api/v1/{id} : Get an invoice by ID
     *
     * @param id ID of the invoice to retrieve (required)
     * @return Details of the invoice (status code 200)
     *         or Invoice not found (status code 404)
     */
    @Operation(
        operationId = "getInvoiceById",
        summary = "Get an invoice by ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Details of the invoice", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceWrapper.class))
            }),
            @ApiResponse(responseCode = "404", description = "Invoice not found")
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1/{id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<InvoiceWrapper> getInvoiceById(
        @Parameter(name = "id", description = "ID of the invoice to retrieve", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * GET /invoices/api/v1/by-propayid/{propayid} : Your GET endpoint
     *
     * @param propayid  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "getInvoiceByPropayId",
        summary = "Your GET endpoint",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceWrapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1/by-propayid/{propayid}",
        produces = { "application/json" }
    )
    
    ResponseEntity<InvoiceWrapper> getInvoiceByPropayId(
        @Parameter(name = "propayid", description = "", required = true, in = ParameterIn.PATH) @PathVariable("propayid") String propayid
    );


    /**
     * GET /invoices/api/v1/{id}/download : Your GET endpoint
     * 
     *
     * @param id  (required)
     * @return Invoice PDF is generated successfully (status code 200)
     *         or Invoice PDF not found (status code 404)
     */
    @Operation(
        operationId = "getInvoicesDownload",
        summary = "Your GET endpoint",
        description = "",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "Invoice PDF is generated successfully", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            }),
            @ApiResponse(responseCode = "404", description = "Invoice PDF not found", content = {
                @Content(mediaType = "application/pdf", schema = @Schema(implementation = org.springframework.core.io.Resource.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/invoices/api/v1/{id}/download",
        produces = { "application/pdf" }
    )
    
    ResponseEntity<org.springframework.core.io.Resource> getInvoicesDownload(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id
    );


    /**
     * PATCH /invoices/api/v1/{id}/status/paid : Mark the status of an invoice as \&quot;paid\&quot;
     *
     * @param id ID of the invoice to update status (required)
     * @param revision  (required)
     * @return Invoice status updated to \&quot;paid\&quot; successfully (status code 200)
     *         or Created (status code 201)
     *         or Invalid input (status code 400)
     *         or Unauthorized (status code 401)
     */
    @Operation(
        operationId = "markInvoiceAsPaid",
        summary = "Mark the status of an invoice as \"paid\"",
        responses = {
            @ApiResponse(responseCode = "200", description = "Invoice status updated to \"paid\" successfully", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response.class))
            }),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "400", description = "Invalid input"),
            @ApiResponse(responseCode = "401", description = "Unauthorized")
        },
        security = {
            @SecurityRequirement(name = "oauth2", scopes={ "tenant:paid" })
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/invoices/api/v1/{id}/status/paid",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Response> markInvoiceAsPaid(
        @Parameter(name = "id", description = "ID of the invoice to update status", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "Revision", description = "", required = true) @Valid @RequestBody Revision revision
    );


    /**
     * PATCH /invoices/api/v1/{id} : 
     *
     * @param id  (required)
     * @param invoicePatch  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "patchInvoiceDetails",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = "/invoices/api/v1/{id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Response> patchInvoiceDetails(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "InvoicePatch", description = "") @Valid @RequestBody(required = false) InvoicePatch invoicePatch
    );


    /**
     * POST /invoices/api/v1/{id}/comment : Post comment on Purchase Request
     *
     * @param id  (required)
     * @param comment  (optional)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "postComment",
        summary = "Post comment on Purchase Request",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/invoices/api/v1/{id}/comment",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<Response> postComment(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "Comment", description = "") @Valid @RequestBody(required = false) Comment comment
    );


    /**
     * POST /invoices/api/v1/{id}/upload : Upload document(s)
     *
     * @param id  (required)
     * @param files List of files to upload (required)
     * @param fileTags  (required)
     * @return OK (status code 200)
     */
    @Operation(
        operationId = "uploadFiles",
        summary = "Upload document(s)",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Response.class))
            })
        },
        security = {
            @SecurityRequirement(name = "oauth2")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/invoices/api/v1/{id}/upload",
        produces = { "application/json" },
        consumes = { "multipart/form-data" }
    )
    
    ResponseEntity<Response> uploadFiles(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") String id,
        @Parameter(name = "files", description = "List of files to upload", required = true) @RequestPart(value = "files", required = true) List<MultipartFile> files,
        @Parameter(name = "fileTags", description = "", required = true) @Valid @RequestPart(value = "fileTags", required = true) FileTags fileTags
    );

}
